version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
